# Changes here will be overwritten by Copier
_commit: v1.4.4-6-g94ac891
_src_path: gh:lincc-frameworks/python-project-template
author_email: t.j.wilson@exeter.ac.uk
author_name: Tom J Wilson
create_example_module: false
custom_install: true
include_benchmarks: true
include_docs: true
include_notebooks: true
mypy_type_checking: none
package_name: macauff
preferred_linter: pylint
project_license: none
project_name: macauff
project_organization: macauff
use_gitlfs: none
use_isort: true
